### ISSUE TITLE
UTF-8 not supported when adding items

### ISSUE THREAD

**Issue by ghost** [ElectricDynamite/pasty-app-web#1]
When adding items, anything but ASCII will provoke 500: Malformed Answer because of an illegal token (Malformed JSON?)

**Comment by ElectricDynamite** [comment]
The issue was the way pastyclient-node was computing the "Content-Length" when POSTing or PUTing to pasty-server.
Following common examples `postData.length` was used. Since UTF-8 needs two bytes per charakter this means that it an HTTP request including UTF-8 data would contain twice as many bytes than the request header specified.
Switching to `Buffer.byteLength(postData)` does the trick.
